package com.jit.demo.mappers;

import com.jit.demo.models.DeviceState;
import com.jit.demo.models.DeviceStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface DeviceStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int countByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int deleteByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int insert(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int insertSelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    List<DeviceState> selectByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    DeviceState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceState record, @Param("example") DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByExample(@Param("record") DeviceState record, @Param("example") DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByPrimaryKey(DeviceState record);

    String selectDeviceStateStatus(DeviceState deviceState);

}