package com.jit.demo.mappers;

import com.jit.demo.models.DeviceOnline;
import com.jit.demo.models.DeviceOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface DeviceOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int countByExample(DeviceOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int deleteByExample(DeviceOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int insert(DeviceOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int insertSelective(DeviceOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    List<DeviceOnline> selectByExample(DeviceOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    DeviceOnline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceOnline record, @Param("example") DeviceOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByExample(@Param("record") DeviceOnline record, @Param("example") DeviceOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_online
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    int updateByPrimaryKey(DeviceOnline record);

    int updateDeviceOffline(DeviceOnline record);

}