package com.jit.demo.mappers;

import com.jit.demo.models.UserBindingDevice;
import com.jit.demo.models.UserBindingDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface UserBindingDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int countByExample(UserBindingDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int deleteByExample(UserBindingDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int insert(UserBindingDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int insertSelective(UserBindingDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    List<UserBindingDevice> selectByExample(UserBindingDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    UserBindingDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserBindingDevice record, @Param("example") UserBindingDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int updateByExample(@Param("record") UserBindingDevice record, @Param("example") UserBindingDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int updateByPrimaryKeySelective(UserBindingDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    int updateByPrimaryKey(UserBindingDevice record);

    List<String> selectByUserId(int userid);

}