package com.jit.demo.models;

public class AutoStart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.id
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.timein_first
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String timeinFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.timein_second
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String timeinSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.timein_third
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String timeinThird;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.timein_fourth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String timeinFourth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_start.timein_fifth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String timeinFifth;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_start
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public AutoStart(Integer id, String deviceNumber, String timeinFirst, String timeinSecond, String timeinThird, String timeinFourth, String timeinFifth) {
        this.id = id;
        this.deviceNumber = deviceNumber;
        this.timeinFirst = timeinFirst;
        this.timeinSecond = timeinSecond;
        this.timeinThird = timeinThird;
        this.timeinFourth = timeinFourth;
        this.timeinFifth = timeinFifth;
    }

    public AutoStart(String deviceNumber, String timeinFirst, String timeinSecond, String timeinThird, String timeinFourth, String timeinFifth) {
        this.deviceNumber = deviceNumber;
        this.timeinFirst = timeinFirst;
        this.timeinSecond = timeinSecond;
        this.timeinThird = timeinThird;
        this.timeinFourth = timeinFourth;
        this.timeinFifth = timeinFifth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_start
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public AutoStart() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.id
     *
     * @return the value of auto_start.id
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.id
     *
     * @param id the value for auto_start.id
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.device_number
     *
     * @return the value of auto_start.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.device_number
     *
     * @param deviceNumber the value for auto_start.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.timein_first
     *
     * @return the value of auto_start.timein_first
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getTimeinFirst() {
        return timeinFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.timein_first
     *
     * @param timeinFirst the value for auto_start.timein_first
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setTimeinFirst(String timeinFirst) {
        this.timeinFirst = timeinFirst == null ? null : timeinFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.timein_second
     *
     * @return the value of auto_start.timein_second
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getTimeinSecond() {
        return timeinSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.timein_second
     *
     * @param timeinSecond the value for auto_start.timein_second
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setTimeinSecond(String timeinSecond) {
        this.timeinSecond = timeinSecond == null ? null : timeinSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.timein_third
     *
     * @return the value of auto_start.timein_third
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getTimeinThird() {
        return timeinThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.timein_third
     *
     * @param timeinThird the value for auto_start.timein_third
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setTimeinThird(String timeinThird) {
        this.timeinThird = timeinThird == null ? null : timeinThird.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.timein_fourth
     *
     * @return the value of auto_start.timein_fourth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getTimeinFourth() {
        return timeinFourth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.timein_fourth
     *
     * @param timeinFourth the value for auto_start.timein_fourth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setTimeinFourth(String timeinFourth) {
        this.timeinFourth = timeinFourth == null ? null : timeinFourth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_start.timein_fifth
     *
     * @return the value of auto_start.timein_fifth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getTimeinFifth() {
        return timeinFifth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_start.timein_fifth
     *
     * @param timeinFifth the value for auto_start.timein_fifth
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setTimeinFifth(String timeinFifth) {
        this.timeinFifth = timeinFifth == null ? null : timeinFifth.trim();
    }
}