package com.jit.demo.models;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_name
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_type
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.from_company
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    private String fromCompany;


    private String simID;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public DeviceInfo(String deviceNumber,
                      String deviceName,
                      String deviceType,
                      String fromCompany,
                      String simID) {
        this.deviceNumber = deviceNumber;
        this.deviceName = deviceName;
        this.deviceType = deviceType;
        this.fromCompany = fromCompany;
        this.simID = simID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public DeviceInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_number
     *
     * @return the value of device_info.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_number
     *
     * @param deviceNumber the value for device_info.device_number
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    public DeviceInfo(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_name
     *
     * @return the value of device_info.device_name
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_name
     *
     * @param deviceName the value for device_info.device_name
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_type
     *
     * @return the value of device_info.device_type
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_type
     *
     * @param deviceType the value for device_info.device_type
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    public String getSimID() {
        return simID;
    }

    public void setSimID(String simID) {
        this.simID = simID == null ? null : simID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.from_company
     *
     * @return the value of device_info.from_company
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public String getFromCompany() {
        return fromCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.from_company
     *
     * @param fromCompany the value for device_info.from_company
     *
     * @mbggenerated Wed Apr 04 12:37:59 CST 2018
     */
    public void setFromCompany(String fromCompany) {
        this.fromCompany = fromCompany == null ? null : fromCompany.trim();
    }
}