package com.jit.demo.models;

import java.util.Date;

public class UserBindingDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding_device.id
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding_device.userid
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding_device.device_number
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding_device.confirm
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    private Boolean confirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding_device.binding_time
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    private Date bindingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public UserBindingDevice(Integer id, Integer userid, String deviceNumber, Boolean confirm, Date bindingTime) {
        this.id = id;
        this.userid = userid;
        this.deviceNumber = deviceNumber;
        this.confirm = confirm;
        this.bindingTime = bindingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding_device
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public UserBindingDevice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding_device.id
     *
     * @return the value of user_binding_device.id
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding_device.id
     *
     * @param id the value for user_binding_device.id
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding_device.userid
     *
     * @return the value of user_binding_device.userid
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding_device.userid
     *
     * @param userid the value for user_binding_device.userid
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding_device.device_number
     *
     * @return the value of user_binding_device.device_number
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding_device.device_number
     *
     * @param deviceNumber the value for user_binding_device.device_number
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber == null ? null : deviceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding_device.confirm
     *
     * @return the value of user_binding_device.confirm
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public Boolean getConfirm() {
        return confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding_device.confirm
     *
     * @param confirm the value for user_binding_device.confirm
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public void setConfirm(Boolean confirm) {
        this.confirm = confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding_device.binding_time
     *
     * @return the value of user_binding_device.binding_time
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public Date getBindingTime() {
        return bindingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding_device.binding_time
     *
     * @param bindingTime the value for user_binding_device.binding_time
     *
     * @mbggenerated Mon May 21 09:48:30 CST 2018
     */
    public void setBindingTime(Date bindingTime) {
        this.bindingTime = bindingTime;
    }
}